### ISSUE TITLE
Port to WebPack

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-browser#8]
Nowadays we're using NPM for module installs also with browser, and webpack for building.

grunt-noflo-browser has to functionality needed for these builds.

However, there are two blockers:

* grunt-noflo-browser component loader doesn't support live programming features:
  - [x] getSource <sup>noflo/grunt-noflo-browser#13</sup>
  - [ ] setSource <sup>noflo/grunt-noflo-browser#14</sup>
* some of our dependencies are not yet available on NPM. Missing:
  - [x] noflo-runtime-iframe
  - [ ] noflo-draggabilly (d4)
  - [x] noflo-gum (forrest)
  - [x] noflo-seriously (forrest)
  - [ ] noflo-prompts (alfa256)
  - [x] noflo-clmtrackr (forrest)
  - [x] noflo-webaudio
  - [x] noflo-tween

**Comment by jonnor** [comment]
Should drop `noflo-3dprint`, not generally useful.

**Comment by automata** [comment]
@bergie done https://www.npmjs.com/package/noflo-webaudio

**Comment by bergie** [comment]
With current build in #9 the size of the generated JS bundle drops from 9MB to 5MB
